""" Each new term in the Fibonacci sequence is generated by
    adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not
    exceed four million, find the sum of the even-valued terms. """

maximo = 4000000
    
|#soma de 1 + 2
soma = 2
somapares = 0

buffer1 = 1
buffer2 = 2

while (buffer1 < maximo) and (buffer2 < maximo):
    
    
    #se for par
    if (soma % 2 == 0):
        somapares = somapares + soma
        print (somapares)

    soma = buffer1 + buffer2
    buffer1 = buffer2
    buffer2 = soma

